### ISSUE TITLE
Can't send file

### ISSUE THREAD

**Issue by hartfordfive** [send-to/sendto#5]
For some reason, anything i try to send i just get the following error:

``` bash
2016/02/16 14:59:25 Sorry, an error occurred:
    EOF
```

What could be causing this?

**Comment by MatthewVance** [comment]
Hi @hartfordfive, would you please provide some more details to help narrow down where the problem might be:
- Which platform were you trying to send from (Linux, Mac, or Windows)?
- What was the name and type of file?
- Where you using the command line or something like the provided Automator workflow?

**Comment by MatthewVance** [comment]
I just downloaded a file I sent to myself and am getting a similar error when trying to decrypt it from my Linux box. I downloaded via `curl -l https://sendto.click/files/1/download -o example.txt.zip.gpg`. The error message I received when running `gpg --decrypt example.txt.zip.gpg` was:

``` bash
gpg: no valid OpenPGP data found.
gpg: decrypt_message failed: eof
```

**Comment by hartfordfive** [comment]
I'm on a Mac and I was attempting to send a simple "test.txt" text file.  I'm using the command line tool, which I installed from the Go source.  If I attempt to send the file to the "demo" user, it works just fine, but if I attempt to send it to myself, that's when I get the error.

**Comment by kennygrant** [comment]
Sorry for the delay in getting back to you, I'll look into it.

**Comment by kennygrant** [comment]
@MatthewVance, you can't download files that way I'm afraid (without authentication), you can only download your files, and only when logged in, you'll instead get a 404 or 401 (add the -v option to curl to see it). So that'll be why decryption failed, I think that's unrelated to this issue.

**Comment by kennygrant** [comment]
@hartfordfive, the problem was isolated to your username I think, I've just looked into this. I've added better logging so it will be clearer where the issue is and pinpoint this problem. 

It's because you're not using a PGP key - you need a public **pgp** key generated with pgp tools (I'd recommend keybase, but macpgp is fine too). In theory we could support other key types like rsa but I'd prefer to keep this simple if possible and it only supports pgp keys just now. I'll add some text to make that clear on user setup. At present the app doesn't do key generation or decryption, though that will probably be added at some point, so you're expected to have pgp tools installed already as the recipient (senders don't need them obviously).

If you'd like a keybase invite let me know, I think I have one left.

**Comment by kennygrant** [comment]
One final point, if you do replace your key, be sure to delete ~/.sendto, because this will contain the bogus incorrect key. At present it doesn't support replacing keys and only downloads once on first use.

**Comment by hartfordfive** [comment]
@kennygrant thanks for the info. I'll try creating a key with macpgp and test that out. Also, I'd appreciate a keybase invite if you still have one left.

Thanks.

**Comment by hartfordfive** [comment]
@kennygrant I also take it that I'll have to create a new user?  I can't see of any way that I'll be able to change my key as I had to enter my public when I signed up and there doesn't appear to be an option to change it.

**Comment by kennygrant** [comment]
Email me at kennygrant  at the domain gmail.com for the invite. Re editing users, if you email me I'll give you instructions on that, sorry I don't have a link exposed for it as yet but it is possible to edit your own user.
